<?php

namespace Config\UserBundle\Entity\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    public function findOneByCode($code)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT u FROM ConfigUserBundle:User u
                            WHERE u.code = :code
                            ')
        ->setParameter('code',$code);
        //$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        $result = $query->getResult();
        return $result?$result[0]:null;
        
    }
}
