<?php

namespace Config\MediaBundle\Entity\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectMedia($offset = 0)
    {
        $count = $this->getEntityManager()
            ->createQuery('SELECT count(m) FROM ConfigMediaBundle:Media m
                            ');
        $query = $this->getEntityManager()
            ->createQuery('SELECT m FROM ConfigMediaBundle:Media m
                            ')
            ->setMaxResults(18)
            ->setFirstResult($offset * 18);
        $result = $query->getResult();
        return array('count'=>(int) $count->getSingleScalarResult(),'result'=>$result);
    }
    public function getMediaWithoutGallery($id,$gallery_id)
    {
        
        $query = $this->getEntityManager()
            ->createQuery('SELECT m FROM ConfigMediaBundle:Media m
                            LEFT JOIN m.gallery g
                            WHERE m.id = :id AND g.id = :gall_id 
                            ')
            ->setParameter('id',$id)
            ->setParameter('gall_id',$gallery_id);
        $result = $query->getResult();
        if(!$result){
            return null;
        }
        return $result[0];
    }
}
