da_main:
    resource: "@DAMainBundle/Controller/"
    type:     annotation
    prefix:   /

config_contact:
    resource: "@ConfigContactBundle/Resources/config/routing.xml"
    prefix:   /

config_media:
    resource: "@ConfigMediaBundle/Resources/config/routing.xml"
    prefix:   /

config_user:
    resource: "@ConfigUserBundle/Resources/config/routing/routing.xml"
    prefix:   /

config_admin:
    resource: "@ConfigAdminBundle/Resources/config/routing.xml"
    prefix:   /
    
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /labadmin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /labadmin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /labadmin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /demo/connect

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

facebook_login:
    pattern: /demo/connect/check-facebook

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /development/rest/

upload_rest:
    type:     rest
    resource: Config\MediaBundle\Controller\Rest\UploadRestController

location_rest:
    type:     rest
    resource: DA\MainBundle\Controller\Rest\MapRestController

basket_rest:
    type:     rest
    resource: DA\MainBundle\Controller\Rest\BasketRestController

media_rest:
    type:     rest
    resource: Config\MediaBundle\Controller\Rest\MediaRestController