<?php

namespace Config\ContactBundle\Entity\Repository;

/**
 * InputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputRepository extends \Doctrine\ORM\EntityRepository
{
}
