sonata_doctrine_orm_admin:
  entity_manager: ~
  audit:
    force: true

  templates:
    form:
      - ConfigAdminBundle:ORM:form_admin_fields.html.twig




sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:        ' '                             # Your Application title
    title_logo:   bundles/damain/images/company_logo.png   # Your Application logo path
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display
    templates:
      # default global templates
      # the layout template include javascript/stylesheet to the formatter bundle,
      # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
      layout:  ConfigAdminBundle::standard_layout.html.twig
      ajax:    ConfigAdminBundle::ajax_layout.html.twig

      # default value if done set, actions templates, should extends a global templates
      list:    ConfigAdminBundle:CRUD:list.html.twig
      show:    ConfigAdminBundle:CRUD:show.html.twig
      edit:    ConfigAdminBundle:CRUD:edit.html.twig
    dashboard:
      blocks:
        #- { position: left, type: sonata.admin.block.admin_list }

      groups:
        sonata.admin.group.page:
          on_top:  true
          label: Pages
          icon:  '<i class="fa fa-file-text-o"></i>'
          items:
            - da.page.admin
        sonata.admin.group.hotel:
          on_top:  true
          label:           Hotels
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-h-square"></i>'
          items:
              - hotel.admin

        sonata.admin.group.excursion:
          on_top:  true
          label:           Excursion
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-bus"></i>'
          items:
              - excursion.admin

        sonata.admin.group.transport:
          on_top:  false
          label:           Transport
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-car"></i>'
          items:
              - transfer.admin
              - car.rent.admin
        sonata.admin.group.tour:
          on_top:  false
          label:           Tour
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-map-signs"></i>'
          items:
              - tour.name.admin
              - tour.admin
              - tour.category.admin
        sonata.admin.group.armenia:
          on_top:  true
          label:           Armenia
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-university"></i>'
          items:
              - armenia.admin
        sonata.admin.group.accommodation:
          on_top:  true
          label:           Accommodation
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-home"></i>'
          items:
              - accommodation.admin
        sonata.admin.group.media:
          on_top:  true
          label: Media
          icon:  '<i class="fa fa-file"></i>'
          items:
            - config.media.admin
        sonata.admin.group.gallery:
          on_top:  true
          label: Gallery
          icon:  '<i class="fa fa-picture-o"></i>'
          items:
            - config.gallery.admin
        sonata.admin.group.user:
          on_top:  true
          label:           Users
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-users"></i>'
          items:
              - sonata.user.admin.user
        sonata.admin.group.service:
          on_top:  true
          label:           Service
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-tasks"></i>'
          items:
              - service.admin
        sonata.admin.group.order:
          on_top:  true
          label:           Order
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-shopping-cart"></i>'
          items:
              - order.admin
        sonata.admin.group.groups:
          on_top:  true
          label:           Groups
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-cogs"></i>'
          items:
              - sonata.user.admin.group
        sonata.admin.group.location:
          on_top:  true
          label:           Location
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-map-marker"></i>'
          items:
              - location.admin
        sonata.admin.group.comfort:
          on_top:  true
          label:           Comfort
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-archive"></i>'
          items:
              - comfort.admin
        sonata.admin.group.settings:
          on_top:  false
          label:           Settings
          label_catalogue: SonataAdminBundle
          icon:            '<i class="fa fa-cog"></i>'
          items:
              - social.admin
        sonata.admin.group.Plugins:
          label:           Plugins
          label_catalogue: SonataAdminBundle
          icon: '<i class="fa fa-plug"></i>'
          items:
              - config.youtube.admin
              - config.contact.admin
              - slider.admin



#    assets:
#        stylesheets:
            # The sandbox includes default pre-optimized version of some css and js
            # So you can either use them, and add your custom assets here
            #   ~ or ~
            # tweak the assetic.yml and the following lines
#            - bundles/sonataformatter/markitup/skins/sonata/style.css
#            - bundles/sonataformatter/markitup/sets/markdown/style.css
#            - bundles/sonataformatter/markitup/sets/html/style.css
#            - bundles/sonataformatter/markitup/sets/textile/style.css
#            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
#            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
#            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
#            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
#            - bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css
#            - bundles/sonataadmin/vendor/select2/select2.css
#            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
#            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
#            - bundles/sonataadmin/css/styles.css
#            - bundles/sonataadmin/css/layout.css
#            - bundles/sonatapage/sonata-page.back.min.css

#        javascripts:
#            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.core.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.widget.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.mouse.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.draggable.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.droppable.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.resizable.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.selectable.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.sortable.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.accordion.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.autocomplete.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.button.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.datepicker.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.dialog.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-blind.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-bounce.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-clip.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-drop.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-explode.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fade.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fold.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-highlight.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-pulsate.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-scale.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-shake.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-slide.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-transfer.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.menu.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.position.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.progressbar.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.slider.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.spinner.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tabs.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tooltip.js
#            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
#            - bundles/sonataadmin/jquery/jquery.form.js
#            - bundles/sonataadmin/jquery/jquery.confirmExit.js
#            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.js
#            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
#            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
#            - bundles/sonataadmin/vendor/select2/select2.min.js
#            - bundles/sonataadmin/App.js
#            - bundles/sonataadmin/Admin.js
#            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
#            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
#            - bundles/sonataformatter/markitup/sets/markdown/set.js
#            - bundles/sonataformatter/markitup/sets/html/set.js
#            - bundles/sonataformatter/markitup/sets/textile/set.js
#            - bundles/sonatapage/sonata-page.back.js
