<?php

namespace DA\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * AccommodationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccommodationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAccommodationByCategory($slug)
    {

        $query = $this->getEntityManager()
            ->createQuery('SELECT a FROM DAMainBundle:Accommodation a
                            WHERE a.category = :slug
                            ')
            ->setParameter('slug',$slug);
        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        $result = $query->getResult();
        if(!$result){
            return null;
        }
        return $result;
    }
    public function filterA($slug,$c,$star)
    {

        $em = $this->getEntityManager()->createQueryBuilder();
        $query = $em
            ->select('a')
            ->from('DAMainBundle:Accommodation', 'a')
            ->where('a.category = :slug')
            ->setParameter('slug', $slug)
        ;
        if($c != '0'){
            $query->andwhere('a.location = :city' );
            $query->setParameter('city', $c);
        }
        if($star != '0'){
            $query->andwhere('a.rooms = :star' );
            $query->setParameter('star', $star);
        }
        $q = $query->getQuery(); 
        $q->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

        $result = $q->getResult();

        if(!$result){
            return null;
        }
        return $result;
    }
    public function getBestPriceAccommodationByCategory($slug)
    {

        $query = $this->getEntityManager()
            ->createQuery('SELECT a FROM DAMainBundle:Accommodation a
                            WHERE a.category = :slug and a.best_price = TRUE 
                            ')
            ->setParameter('slug',$slug);
        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        $result = $query->getResult();
        if(!$result){
            return null;
        }
        return $result;
    }
    
    public function getAccommodationBySlug($slug)
    {

        $query = $this->getEntityManager()
            ->createQuery('SELECT a FROM DAMainBundle:Accommodation a
                            WHERE a.slug = :slug
                            ')
            ->setParameter('slug',$slug);
        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        $result = $query->getResult();
        if(!$result){
            return null;
        }
        return $result[0];
    }
    
    public function getAccommodationCity($slug)
    {

        $query = $this->getEntityManager()
            ->createQuery('SELECT l FROM DAMainBundle:Location l
                            JOIN l.accommodation a
                            WHERE a.category = :slug
                            ')
            ->setParameter('slug',$slug);
        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        $result = $query->getResult();
        if(!$result){
            return null;
        }
        return $result;
    }

    public function getAccommodationInCity($location)
    {
        $query = $this->getEntityManager()

            ->createQuery('SELECT a,RAND() as HIDDEN rand FROM DAMainBundle:Accommodation a
                            WHERE a.location = :location
                            ORDER BY  rand
                            ')
            ->setParameter('location',$location)
            ->setMaxResults(3);
        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        $result = $query->getResult();
        
        if(!$result){
            return null;
        }
        return $result;
    }
}
