<?php

namespace DA\MainBundle\Entity\Repository;

/**
 * CarRentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRentRepository extends \Doctrine\ORM\EntityRepository
{
}
