<?php

namespace DA\MainBundle\Entity\Repository;
use Doctrine\ORM\Query;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getServiceBySlug($slug)
    {

        $query = $this->getEntityManager()
            ->createQuery('SELECT s FROM DAMainBundle:Service s
                            WHERE s.slug = :slug
                            ')
            ->setParameter('slug',$slug);
        $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
        $result = $query->getResult();
        if(!$result){
            return null;
        }
        return $result[0];
    }
}
